### ISSUE TITLE
rwtodd / TradeRisk  how to execute 

### ISSUE THREAD

**Issue by asraghu123** [rwtodd/TradeRisk#1]
Hi Richard,

  Can you provide some instructions on how to run this package ? 

Regards,
asraghu

**Comment by rwtodd** [comment]
To build the windows one you'd need msbuild tools.   I built it now for you for 64-bit windows 10, if that helps:

[TradeRisk.zip](https://github.com/rwtodd/TradeRisk/files/5794080/TradeRisk.zip)

It's just a tool to help visualize risk amounts (in term of dollars and 'R'-multiples) if you adjust your position across a price ladder.  It makes it easy to judge, like, "if I double my position at 27.40, where does my stop have to go if I only want to loose $1400 on this trade?"  That kind of thing.

There are dialog boxes to change the instrument and center price of the ladder.  Also, if you press the numbers 0-9 it will adjust he number of contracts to buy and sell with each click.

**Comment by asraghu123** [comment]
Thanks.
